gimkana/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index', ),
    url(r'^$', views.QrListView.as_view(), name='qrs'),

    # url(r'^qrs/$', views.QrListView.as_view(), name='qrs'),
    url(r'^qrs/$', views.QrListView.as_view(), name='qrs'),
    # url(r'^myqrs/$', views.UserQrListView.as_view(), name='myqrs'),

    url(r'^qr/(?P<pk>.+)$', views.QrDetailView.as_view(), name='qr-detail'),

    # url(r'^qrscan/$', views.userqr.UserQrTestCreateView.as_view(), name='qrscan-test'),
    url(r'^qrscan/(?P<pk>.+)$', views.UserQrCreateView.as_view(), name='qrscan'),
    url(r'^gethint/(?P<pk>.+)$', views.UserQrGetHintView.as_view(), name='get-hint'),

    url(r'^rules/$',
        login_required(TemplateView.as_view(template_name='gimkana/rules.html'), login_url='signup'),
        name='rules'),
    url(r'^about/$', TemplateView.as_view(template_name='gimkana/about.html'), name='about'),
    url(r'^notstarted/$', TemplateView.as_view(template_name='gimkana/not_started.html'), name='not-started'),

    # url(r'^users/$', views.UserListView.as_view(), name='users'),
    url(r'^users/$', views.active_user_list_view, name='users'),
]

gimkana/models/userqr.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns

from .qr import Qr


class UserQr(models.Model):
    id = models.AutoField(primary_key=True)
    qr = models.ForeignKey(Qr, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_shop = models.BooleanField(null=False, blank=False)
    hints = models.IntegerField(blank=True, default=0)
    scan_date = models.DateTimeField(blank=True, null=True)
    value = models.IntegerField(blank=True, null=True)

    @property
    def is_scanned(self):
        return bool(self.scan_date or self.value == 0)

    class Meta:
        # ordering = ['qr__num_order']
        unique_together = ['qr_id', 'user_id']

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1}) scanned by {2} on {3} - {4}'\
            .format(self.qr.id, self.qr.title, self.user.username, self.scan_date, self.value)

    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de QR
        """
        return reverse('qr-detail', args=[str(self.id)])

gimkana/templates/gimkana/about.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="Center">
        <p>El código del proyecto es <strong>Open Source</strong>.</p>
        <p>Si deseas descargarte el código, escribe a <a href="mailto:penya.freestayl@gmail.com">penya.freestayl@gmail.com</a>.</p>
        <br>
        <h4><strong>AGRADECIMIENTOS</strong></h4>
        <p>Alvaro Sánchez</p>
        <p>Arantxa Solares</p>
        <p>Daniel Martínez</p>
        <p>Felipe Rodríguez</p>
        <p>Karla Banda</p>
        <p>Lara Rodríguez</p>
        <p><a href="https://marcjavierre.com/">Marc Javierre-Kohan</a></p>
        <p>Pablo Martín</p>
        <p>Rafael Pellón</p>
        <p>Sandra Iañez</p>
        <p><a href="https://www.9barrisimatge.org/">9 Barris Imatge</a></p>
        <p>A mis padres, que me regalaron el ZX-Spectrum con el que comencé a programar</p>
    </div>

    <form class="Center" action="{% url 'rules' %}">
        <input class="Button" type="submit" value="Volver"/>
    </form>

{% endblock %}

gimkana/templates/gimkana/not_started.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="Center">
        <h3>LA GIMKANA COMIENZA</h3>
        <h3>EL <strong>29-05-2021</strong> A LAS <strong>00:00</strong></h3>
    </div>
    <br>

    <form class="Center" action="{% url 'rules' %}">
        <input class="Button" type="submit" value="Ver reglas"/>
    </form>

{% endblock %}

gimkana/templates/gimkana/qr_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h4>{{ qr.title }}</h4>

    {% if qr.is_shop %}
        {# <p></p><strong>Puntos: {{ qr.scoring_value }}</strong></p> #}
        <br>
        <img src="/static/img/qr/comercios.jpg" alt="Comercio colaborador">
        <br>
        <div class="Description">
            <p>Los Comercios Colaboradores son el principal ingreso de la Festa Major. Sin ellos, las fiestas no serían posibles tal y como las conocemos.</p>
            <p>Por eso, cuando compras en los comercios del barrio, estás colaborando con la Festa Major.</p>
            <p style="text-align: left;">Además:
                - Son nuestros vecinos y vecinas
                - Ofrecen un trato personal y cercano
                - Sufren la competencia de las grandes superficies y el comercio electrónico
                - Un barrio sin comercios es un barrio muerto
            </p>
        </div>
    {% else %}
        {# <p></p><strong>Puntos: {{ qr.scoring_value }} - Pistas: {{ qr.hints }}</strong></p> #}

        {% if not qr.is_scanned %}
            <p class="Justify">{{ qr.hint|safe }}</p>
        {% endif %}

        {% if qr.is_scanned or qr.hints > 0 %}
            <br>
            <figure>
                <img src="/static/{{ qr.image }}" alt="{{ qr.title }}">
                <figcaption>{{ qr.image_footer }}</figcaption>
            </figure>
            <br>
        {% endif %}

        {% if qr.is_scanned %}
            <div class="Description">
                {{ qr.description|safe|urlize }}
            </div>
        {% else %}
            {% if qr.hints > 1 %}
                <a class="MapUrl" href="{{ qr.coordinates }}">Pulsa para abrir el mapa</a>
                <div class="GoogleMapsContainer">
                    <a href="{{ qr.coordinates }}">
                        <img src="/static/img/maps/{{ qr.id }}.jpg" alt="{{ qr.title }}">
                    </a>
                </div>
            {% endif %}
        {% endif %}
    {% endif %}

    <div>
        <div class="ButtonsContainer">
            {% if qr.is_shop is not True and qr.is_scanned is not True %}
                {% if qr.hints < 2 %}
                    <form action="{% url 'get-hint' qr.id %}">
                        <input class="Button" type="submit" value="Abrir pista*"/>
                    </form>
                {% else %}
                    <form action="{% url 'get-hint' qr.id %}">
                        <input class="Button" type="submit" value="Resolver QR*"/>
                    </form>
                {% endif %}
            {% endif %}

            <form action="{% url 'qrs' %}">
                <input class="Button" type="submit" value="Ver QRs"/>
            </form>
        </div>

        {% if qr.is_shop is not True and qr.is_scanned is not True %}
            <div class="Warning Center">
                {% if qr.hints < 2 %}
                    * Cada pista resta 1 punto al QR
                {% else %}
                    * Si resuelves el QR no se obtendrán puntos
                {% endif %}
            </div>
        {% endif %}
    </div>

{% endblock %}

gimkana/templates/gimkana/qr_list.html
{% extends "base_generic.html" %}

{% block content %}
    {% include "gimkana/scoring.html" %}

    {% for qr in qr_list %}
        <div class="list-item
                {% if qr.is_scanned %}
                    checked
                {% elif not qr.is_available %}
                    unavailable
                {% else %}
                    unchecked
                {% endif %}"
        >
            <a href="{{ qr.get_absolute_url }}">{{ qr.title }}</a>
        </div>
    {% empty %}
        <p>Aún no hay QRs.</p>
    {% endfor %}

    <form class="Center" action="{% url 'rules' %}">
        <input class="Button" type="submit" value="Ver reglas"/>
    </form>

    {% if request.user.is_staff %}
        <form class="Center" action="{% url 'users' %}">
            <input class="Button" type="submit" value="Ranking"/>
        </form>
    {% endif %}



{% endblock %}

gimkana/templates/gimkana/qrscan_detail.html
{% extends "gimkana/qr_detail.html" %}

gimkana/templates/gimkana/rules.html
{% extends user.is_authenticated|yesno:"base_generic.html,base_empty.html" %}

{% block content %}
    <div class="Center">
        <h2><strong>GIMKANA</strong></h2>
        <img src="/static/img/logo-freestayl.png" alt="FreeStayl" width="70%">
    </div>
    <br>

    <div class="Justify">
        <p>Bienvenid@ a la Gimkana FreeStayl sobre la Festa Major de la Prospe.</p>
        <p>El objetivo del juego es encontrar y escanear el máximo número de QRs que están distribuidos en zonas representativas de la Festa Major. Podrás conseguirlos desde el <strong>29/5 hasta el 5/6</strong>. </p>
        <p>En la pantalla principal se muestra una lista con todos los QRs. Al entrar en cada uno de ellos encontrarás una pista que te ayudará a descubrir su ubicación. No es necesario resolverlos en orden.</p>
        <p>Aunque los QRs no estarán a simple vista, es posible que encuentres alguno por casualidad. En ese caso ¡enhorabuena!.</p>
        <p>Si lo necesitas, puedes pedir una pista adicional, que consiste en una fotografía de la ubicación del QR.</p>
        <p>Si aún tienes dudas, puedes pedir otra pista, que en este caso será un mapa desde el que podrás navegar para llegar hasta el QR.</p>
        <p>También puedes conseguir puntos extra escaneando los QRs en los <strong>comercios colaboradores</strong> de la Festa Major.</p>
        <p>Las puntuaciones son:
        <ul>
            <li>5 puntos por cada QR</li>
            <li>4 puntos por cada QR con fotografía</li>
            <li>3 puntos por cada QR con mapa</li>
            <li>1 punto por cada QR de comercio</li>
        </ul>
        <p>En caso de empate a puntos, el orden para desempatar será: mayor número de QRs, mayor número de comercios, y menor número de pistas. Si aún así persiste el empate, se aplicará cualquier otro criterio que decida la Peña FreeStayl. Cualquier comportamiento contra el 'juego limpio' conllevará la descalifación para optar a los premios.</p>
        <p><strong>La entrega de premios se realizará el domingo 6/6 a las 14h aproximadamente en la plaza de La zona verde.</strong></p>
        <p>¿Y si no encuentro el QR? Siempre puedes marcarlo como resuelto y ver la información que contiene. En ese caso no conseguirás ningún punto por ese QR.</p>
        <p>Para participar es necesario registrarse. No es necesario utilizar contraseña, ya que el registro está asociado a un único dispositivo móvil.</p>
        <p>Los QRs que consigas una vez finalizado el juego no sumarán puntos adicionales.</p>
        <p>Los datos de registro servirán para contactar a las personas ganadoras y se borrarán una vez finalizada la gimkana.</p>
        <p>Si encuentras algún QR deteriorado o algún fallo en la aplicación, manda un email a <a href="mailto:penya.freestayl@gmail.com">penya.freestayl@gmail.com</a>.</p>
    </div>

    {% if user.is_authenticated %}
        <form class="Center" action="{% url 'qrs' %}">
            <input class="Button" type="submit" value="Jugar"/>
        </form>
    {% endif %}

    <div class="Center">
        <br>
        <p><a href="{% url 'about' %}">Acerca de</a></p>
    </div>

{% endblock %}

gimkana/templates/gimkana/scoring.html
{% block scores %}
<div class="TagsContainer">
    <div class="TagsRow">
        <div class="Tag">
            <div class="Label">
                QRs: {{ num_qrs }} / 24
            </div>
        </div>

        <div class="Tag">
            <div class="Label">
                Comercios: {{ num_shops }}
            </div>
        </div>

        <div class="Tag">
            <div class="Label">
                Pistas: {{ num_hints }}
            </div>
        </div>
    </div>

    <div class="TagsRow">
        <div class="Tag">
            <div class="Label">
                Puntos: {{ score }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

gimkana/templates/gimkana/user_qr_list.html
{% extends "base_generic.html" %}

{% block content %}
    {% include "gimkana/scoring.html" %}

    <h2>Mis QRs</h2>

    {% if userqr_list %}
        {% for userqr in userqr_list %}
            <div class="list-item {% if userqr.is_scanned %}checked{% else %}unchecked{% endif %}">
                <a href="{% url 'qr-detail' userqr.qr.pk %}">{{userqr.qr.title}}</a>
                (Hints: {{ userqr.hints }} - {% if userqr.scan_date %}Scanned {{ userqr.scan_date }}{% else %}Sin escanear{% endif %})
            </div>
        {% endfor %}
    {% else %}
        <p>No has escaneado ningún QR</p>
    {% endif %}
{% endblock %}